### ISSUE TITLE
support for variables

### ISSUE THREAD

**Issue by mybigman** [ap/vim-css-color#134]
```css
:root {
  --gulf-blue: 55, 64, 87;
}

rgb(var(--gulf-blue));
rgba(var(--gulf-blue), 0.5);
```

**Comment by ap** [comment]
Yikes. That will be painful at best, if feasible at all. If not, it may instead be possible to highlight the definition (rather than individual uses). I don’t know. I’ll have to think about it.

Good to know that this is a thing people do in CSS now, though, thanks for alerting me.

**Comment by adityashaw2** [comment]
My use case in CSS is like this:
```css
html {
    --var-color-primary: #9C2646;
    --var-color-secondary: #E2525E;
}

.some-class {
    color: calc(--var-color-secondary);
}
```

If `--var-color-secondary` text inside `calc()` can be highlighted with the defined color, it would be of great help.
