### ISSUE TITLE
Doesn't seem to work with sass maps

### ISSUE THREAD

**Issue by loremipson** [ap/vim-css-color#53]
Example:

```scss
// Color map
$colors: (
  copy: #7d7d7d,
  headings: #454545,
  dark: #020202,
  light: #f7f7f7
);
```

The map typically lives in a settings or config scss file. Then I have a "color" function, which just gets a map value, so I can use it throughout my other scss files like so:

```scss
body {
  color: color(copy);
  background: color(dark);
}
```
Would be pretty neat to get this plugin so it applies to both situations. I realize the latter might be pretty difficult, but getting this to work on the map itself would be awesome.
